[package]
authors = ["Ivan Nejgebauer <inejge@gmail.com>"]
description = "Pure-Rust LDAPv3 Client"
documentation = "https://docs.rs/ldap3"
keywords = ["ldap", "client", "tokio", "async"]
license = "MIT/Apache-2.0"
name = "ldap3"
readme = "README.md"
repository = "https://github.com/inejge/ldap3"
version = "0.7.0-alpha.3"
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["dns", "macros", "io-util", "stream", "sync", "tcp", "time", "uds"] }
tokio-util = { version = "0.3", features = ["codec"] }
bytes = "0.5"
nom = "2"
url = "2"
futures = "0.3.4"
percent-encoding = "2.1.0"
futures-util = "0.3.4"
log = "0.4.8"
lazy_static = "1.4.0"
thiserror = "1.0.15"
native-tls = { version = "0.2.4", optional = true }
tokio-tls = { version = "0.3.0", optional = true }
maplit = "1.0.2"

[dependencies.lber]
path = "lber"
version = "0.1.7"

[dependencies.sspi]
version = "0.1.1"

[[example]]
name = "bind_sync"
required-features = ["sync"]

[[example]]
name = "search_starttls_noverify"
required-features = ["sync", "tls"]

# Only works on Unix
[[example]]
name = "whoami_external"
required-features = ["sync"]

# Only works on Unix
[[example]]
name = "whoami_external_sync"
required-features = ["sync"]

[[example]]
name = "whoami_proxyauth"
required-features = ["sync"]

[features]
default = ["sync", "tls"]
tls = ["native-tls", "tokio-tls"]
sync = ["tokio/rt-core"]

[dev-dependencies]
env_logger = "0.7"

[workspace]
members = [".", "lber"]
